### ISSUE TITLE
Strange escape sequence sent by vim to terminal

### ISSUE THREAD

**Issue by madscientist159** [ciaranm/inkpot#8]
vim appears to send several strange (i.e. undocumented) escape sequences to the underlying terminal when using the inkpot scheme. I have been unable to match them to any VT-100 or ANSI escape codes; was the usage of these sequences intentional?

^[[3231m
^[[4232m
^[[3130m

NOTE: Very few terminal emulators warn on receiving invalid tokens; you may find it easier to redirect the output of vim to a file, then examine its contents to see the problem.

**Comment by ciaranm** [comment]
This isn't something inkpot does, it's somethimg Vim does. Also, Vim doesn't send VT-100 or ANSI escape codes to your terminal, it sends whatever your terminal is listed as supporting in termcap or terminfo.

Are you running into trouble because you're using a terminal which sets TERM=xterm but is not xterm?
